### PR TITLE
[libcommhistory] Run unit tests as privileged user. Contributes to MER#1374

### PR DESCRIPTION
**Pull request by matthewvogt**
Privileged mode is necessary to get predictable behavior from the contacts API. Also prefer to use the contacts database specifically for unit tests rather than the system database.

### CODE REVIEW

**Comment by jpetrell** [comment]
I still get failures http://pastebin.com/aKWH6LQ9, though the device I used wasn't clean. Would be nice to encapsulate tests set so it didn't modify or break due to user data.

**Comment by jpetrell** [comment]
If the tests pass at CI gate LGTM.

**Comment by matthewvogt** [comment]
Try using testrunner-lite, something like:

```
$ testrunner-lite -v -f /opt/tests/libcommhistory-qt5-unit-tests/tests.xml -o ~/test-results.xml
```

**Comment by jpetrell** [comment]
Still no luck http://pastebin.com/gi4vxEEx

**Comment by matthewvogt** [comment]
Recreated as: https://git.merproject.org/mer-core/libcommhistory/merge_requests/1

**Pull request closed without merging**
