### PR TITLE
[libcommhistory] Improve model loading times. Contributes to MER#1174

### PR DESCRIPTION
**Pull request by matthewvogt**
Mostly-complete PR bringing forward special's 'recipient' work, and optimizing the load time of the various models.  The biggest performance change is that recipients in the CommContactGroupModel are not resolved immediately, but individually when the group's contactIds or displayNames property is accessed.

Still some remaining work to clean up various TODOs and finish off some test improvements.  The individual commits have been heavily reworked to give some semblance of logical consistency, but I may have misallocated some changes; if so, please note and I'll try to rectify.  I also want to put the requiredType filtering back in, before the code changes enough to make that problematic.

Some review now would be useful, in case I've misunderstood something: @special @amtep ?

### CODE REVIEW

**Comment by matthewvogt** [comment]
Updated to address some of Chris' comments.

**Comment by matthewvogt** [comment]
@special @amtep 

I'm leaning towards merging this soon to get real user feedback, since there's no data format changes and the whole thing can be easily reverted if problematic.  Any prior input appreciated...

**Comment by chriadam** [comment]
I agree - unless anyone raises concerns very soon, I think we should merge this now.

**Comment by monich** [comment]
Will this break backup/restore functionality by changing serialization format?

**Comment by matthewvogt** [comment]
Serialization format should be unchanged.  DBus serialization is different than previously, but I don't think that is problematic?

**Comment by monich** [comment]
OK, that's good.  DBus serialization doesn't matter, these interfaces are not public.

**Pull request merged**
